Repository AY2223S1-CS2103T-T13-3/tp, pull requests merged in 2022-09, with the labels that each got.

#34 Add Skeletal PPP
  docs/team/josephaedan.md
Labels: v1.1

#35 Update README.md
  README.md
  docs/_sass/minima/_base.scss
Labels: type.Documentation, v1.1

#36 Update AboutUs
  docs/AboutUs.md
  docs/images/josephaedan.png
Labels: type.Documentation, v1.1

#37 Add recruitment status documentation in User Guide
  docs/UserGuide.md
Labels: type.Documentation, v1.1

#40 Add UI Mock Up
  docs/images/Ui.png
Labels: type.Documentation, v1.1

#44 Add Ying Ting's skeletal PPP
  docs/team/yingting.md
Labels: type.Documentation, v1.1

#41 Update AboutUs
  docs/AboutUs.md
  docs/images/yingting.png
Labels: type.Documentation, v1.1

#47 Add Skeletal PPP
  docs/team/marcustan.md
Labels: v1.1

#45 Update UG with skill and note commands
  docs/UserGuide.md
Labels: type.Documentation, v1.1

#43 Update find command of CLinkedIn in UserGuide
  docs/UserGuide.md
  docs/team/ytingtan.md
Labels: type.Documentation, v1.1

#52 Update README.md
  README.md
Labels: type.Documentation

#53 Update _config.yml
  docs/_config.yml
Labels: type.Documentation

#54 Update config
  docs/_config.yml
Labels: type.Documentation

#56 Update user guide
  docs/UserGuide.md
Labels: type.Documentation, v1.1

#59 Update UG to remove AB3 references
  docs/UserGuide.md
Labels: type.Documentation, v1.1
