Repository AY2223S1-CS2103T-T13-3/tp, pull requests merged in 2022-10, with the labels that each got.

#66 Improve Find feature to be more versatile
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/DetailsContainKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: v1.2

#68 #2A: Add functions for calculating total count of candidates
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: v1.2

#76 Ignore binary folder and .class files
  .gitignore
Labels: type.Bug, priority.High

#75 #2C: Add UI Component to display person count
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCountDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonCountDisplay.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: v1.2, type.Task

#77 Recommend Visual Studio Code Extensions
  .vscode/extensions.json
Labels: priority.Low

#83 Add FindPhoneCommand
  src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindPhoneCommandParser.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindPhoneCommandTest.java
  src/test/java/seedu/address/logic/parser/FindPhoneCommandParserTest.java
Labels: v1.2, priority.Low

#84 #1: Add command summary to Help section
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: v1.2

#86 Update Find Commands
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/LocationContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
Labels: v1.2

#91 Update colour scheme to match UI mockup
  src/main/resources/view/DarkTheme.css
Labels: v1.2, priority.Low

#92 Update parser to be case-insensitive when checking commands
  src/main/java/seedu/address/logic/commands/FindEmailCommand.java
  src/main/java/seedu/address/logic/commands/FindLocationCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: v1.2, priority.Medium

#94 Update find command to consolidate all find features
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindEmailCommand.java
  src/main/java/seedu/address/logic/commands/FindLocationCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
  src/main/java/seedu/address/logic/commands/FindStatusCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindEmailCommandParser.java
  src/main/java/seedu/address/logic/parser/FindLocationCommandParser.java
  src/main/java/seedu/address/logic/parser/FindNameCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPhoneCommandParser.java
  src/main/java/seedu/address/logic/parser/FindStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DetailsContainKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindEmailCommandTest.java
  src/test/java/seedu/address/logic/commands/FindLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/FindStatusCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindEmailCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindLocationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindNameCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindPhoneCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindStatusCommandParserTest.java
Labels: v1.2, type.Task, priority.High

#95 Fix EditCommand test case
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug, v1.2

#96 Add UI component for status
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: v1.2, type.Task, priority.High

#103 Fix bug for find command and update for note prefix
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DetailsContainKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniqueTagTypeMap.java
  src/main/java/seedu/address/model/tag/TagType.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
Labels: type.Bug, v1.2b

#110 Update Developer Guide with implementation of Tag Type feature
  docs/DeveloperGuide.md
  src/main/java/seedu/clinkedin/logic/commands/CreateTagTypeCommand.java
  src/main/java/seedu/clinkedin/logic/commands/DeleteTagCommand.java
Labels: type.Documentation, v1.3

#112 Update DG for add/edit/delete tag feature
  docs/DeveloperGuide.md
Labels: type.Documentation

#120 Update DG with implementation for Find Command
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
Labels: type.Documentation, v1.3

#121 Add skeletal files for import and export command
  src/main/java/seedu/clinkedin/logic/commands/ExportCommand.java
  src/main/java/seedu/clinkedin/logic/commands/ImportCommand.java
  src/main/java/seedu/clinkedin/logic/parser/AddCommandParser.java
  src/main/java/seedu/clinkedin/logic/parser/CliSyntax.java
Labels: type.Task, v1.3

#122 Update DG for consistency
  docs/DeveloperGuide.md
Labels: type.Documentation

#125 Add stats command to view statistics of candidates
  src/main/java/seedu/clinkedin/commons/core/Messages.java
  src/main/java/seedu/clinkedin/logic/commands/StatsCommand.java
  src/main/java/seedu/clinkedin/logic/parser/AddressBookParser.java
  src/main/java/seedu/clinkedin/model/Model.java
  src/main/java/seedu/clinkedin/model/ModelManager.java
  src/main/java/seedu/clinkedin/model/person/Person.java
  src/main/java/seedu/clinkedin/model/person/UniqueTagTypeMap.java
  src/test/java/seedu/clinkedin/logic/commands/AddCommandTest.java
  src/test/java/seedu/clinkedin/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/clinkedin/logic/commands/StatsCommandTest.java
Labels: type.Task, v1.3

#134 Add functionality for help command
  src/main/java/seedu/clinkedin/logic/commands/ClearCommand.java
  src/main/java/seedu/clinkedin/logic/commands/HelpCommand.java
  src/main/java/seedu/clinkedin/logic/commands/ListCommand.java
  src/main/java/seedu/clinkedin/logic/parser/AddressBookParser.java
  src/main/java/seedu/clinkedin/logic/parser/CliSyntax.java
  src/main/java/seedu/clinkedin/logic/parser/HelpCommandParser.java
  src/test/java/seedu/clinkedin/logic/commands/HelpCommandTest.java
  src/test/java/seedu/clinkedin/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/clinkedin/logic/parser/HelpCommandParserTest.java
Labels: v1.3

#132 Add undo/redo feature
  src/main/java/seedu/clinkedin/commons/core/Messages.java
  src/main/java/seedu/clinkedin/commons/exceptions/CannotRedoAddressBookException.java
  src/main/java/seedu/clinkedin/commons/exceptions/CannotUndoAddressBookException.java
  src/main/java/seedu/clinkedin/logic/commands/RedoCommand.java
  src/main/java/seedu/clinkedin/logic/commands/UndoCommand.java
  src/main/java/seedu/clinkedin/logic/parser/AddressBookParser.java
  src/main/java/seedu/clinkedin/model/Model.java
  src/main/java/seedu/clinkedin/model/ModelManager.java
  src/main/java/seedu/clinkedin/model/VersionedAddressBook.java
  src/test/java/seedu/clinkedin/logic/commands/AddCommandTest.java
  src/test/java/seedu/clinkedin/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/clinkedin/logic/commands/CommandTestUtil.java
  src/test/java/seedu/clinkedin/logic/commands/RedoCommandTest.java
  src/test/java/seedu/clinkedin/logic/commands/UndoCommandTest.java
  src/test/java/seedu/clinkedin/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/clinkedin/model/ModelManagerTest.java
  src/test/java/seedu/clinkedin/model/VersionedAddressBookTest.java
Labels: type.Task, priority.Medium, v1.3

#138 Update find to include rating and links
  docs/DeveloperGuide.md
  src/main/java/seedu/clinkedin/logic/parser/CliSyntax.java
  src/main/java/seedu/clinkedin/logic/parser/FindCommandParser.java
  src/main/java/seedu/clinkedin/model/person/DetailsContainKeywordsPredicate.java
Labels: priority.High, v1.3

#142 Update Result Display Window to the side
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, v1.3

#141 Change Help Display to display a Table of commands
  src/main/java/seedu/clinkedin/logic/parser/CliSyntax.java
  src/main/java/seedu/clinkedin/ui/HelpWindow.java
  src/main/java/seedu/clinkedin/ui/utils/CommandRow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium, v1.3

#151 Add UI for statistics and modify for ratings
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/emptygx.md
  docs/team/yingting.md
  src/main/java/seedu/clinkedin/commons/core/Messages.java
  src/main/java/seedu/clinkedin/logic/commands/CommandResult.java
  src/main/java/seedu/clinkedin/logic/commands/StatsCommand.java
  src/main/java/seedu/clinkedin/model/Model.java
  src/main/java/seedu/clinkedin/model/ModelManager.java
  src/main/java/seedu/clinkedin/ui/MainWindow.java
  src/main/java/seedu/clinkedin/ui/ResultDisplay.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/clinkedin/logic/commands/AddCommandTest.java
  src/test/java/seedu/clinkedin/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/clinkedin/logic/commands/StatsCommandTest.java
Labels: v1.3

#154 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.Documentation, v1.4

#155 Update help message image in User Guide
  docs/images/helpMessage.png
Labels: type.Documentation, v1.4

#201 Add How to Use section in UG
  docs/UserGuide.md
Labels: v1.4

#203 Update UG for stats and find command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation, v1.4
