Repository AY2223S1-CS2103T-T13-3/tp, pull requests merged in 2022-11, with the labels that each got.

#207 Add some reuse credit
  README.md
  docs/UserGuide.md
  src/main/java/seedu/clinkedin/logic/commands/CommandResult.java
  src/main/java/seedu/clinkedin/ui/MainWindow.java
  src/main/java/seedu/clinkedin/ui/ResultDisplay.java
Labels: type.Documentation

#208 Update Marcus' PPP for early draft
  docs/team/emptygx.md
Labels: type.Documentation, type.Task, v1.4

#212 Fix links being displayed as a single line
  src/main/java/seedu/clinkedin/model/person/Person.java
Labels: type.Bug, v1.4

#211 Fix Piechart overlay when executing 'stats'
  src/main/java/seedu/clinkedin/ui/ResultDisplay.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, v1.4

#216 Fix: Missing commands in help window
  src/main/java/seedu/clinkedin/logic/commands/EditCommand.java
  src/main/java/seedu/clinkedin/logic/commands/ExitCommand.java
  src/main/java/seedu/clinkedin/logic/parser/CliSyntax.java
Labels: Must fix

#243 Fix stats bugs
  src/main/java/seedu/clinkedin/logic/commands/FindCommand.java
  src/main/java/seedu/clinkedin/model/ModelManager.java
  src/main/java/seedu/clinkedin/ui/MainWindow.java
  src/main/java/seedu/clinkedin/ui/ResultDisplay.java
Labels: type.Bug, v1.4, Good to fix

#285 2101 UG
  docs/UserGuide.md
  docs/images/ExportWindow.png
  docs/images/ImportWindow.png
  docs/images/img.png
  docs/images/img_1.png
Labels: type.Documentation, v1.5
